# From: https://github.com/marketplace/actions/arduino-arduino-lint-action
name: Arduino Lint

on:
  push:
  workflow_dispatch:

jobs:
  arduino-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          compliance: strict
          verbose: true
